### ISSUE TITLE
OUT with Immediate Value Error

### ISSUE THREAD

**Issue by Valsamon** [swanlizard/a72#1]
If I use OUT with an immediate value A72 v1.03 gives a "Reserved word misuse" error, something that obviously shouldn't happen.

**Comment by swanlizard** [comment]
Hi!  Sorry for the late reply!!  Thank you for letting me know!  I rewrote the entire IN/OUT handler and tested it--it does what it's told to now.  I'll be uploading the fixed version immediately after responding.

**Comment by Valsamon** [comment]
Thanks for the reply and the quick fix!
