### ISSUE TITLE
Licensing question about distribution

### ISSUE THREAD

**Issue by mateuszviste** [swanlizard/a72#3]
Hello,

Thank you for A72, it is a very nice, minimalist tool (I do have a few minor remarks, but that will be explicited in different issues). The question I have here is about licensing. Do you allow redistribution of A72's binaries and sources? I have packaged A72 and added it to the SvarDOS repository (link below). I hope that's fine.

http://svardos.org/?p=repo

**Comment by swanlizard** [comment]
Hi!  I released A72 as public domain, so you are free to make with it as you see fit!  Also thank you for bringing the issues to my attention!  I'll address them in the order that they are fixed!
