### ISSUE TITLE
LF files lead to cryptic error

### ISSUE THREAD

**Issue by mateuszviste** [swanlizard/a72#4]
When I try to assemble an ASM file with LF endings, A72 v1.04 only outputs a confusing error "garbage past end". Took me a couple of minutes to figure out it was because of line endings.

Perhaps the error message could be clearer? Or LF-only files supported? Or the limitation documented?

**Comment by swanlizard** [comment]
LF is now accepted as a valid line terminator (but still replaced with a provisional CR on read for purposes of internal handling)
