### ISSUE TITLE
support for "jz short label" (nasm compat)

### ISSUE THREAD

**Issue by mateuszviste** [swanlizard/a72#5]
A72 outputs a "reserved word" error on conditional jumps suffixed by the "short" word. For example: ```jne short label```.

I know that such jumps can technically only be short, but this syntax is supported by nasm. When short is not specified and the label is too far away, nasm emulates a long conditional jump. Such trick is not supported by A72 and it's perfectly fine, but still - the "short" word could maybe act as a no-op, if only for nasm compatibility?

**Comment by swanlizard** [comment]
The G5 handler does not check for size overrides in the rewrite, making them effectively bogus now (in G5 at least)
