### ISSUE TITLE
Parsing silently stops at first line longer than 125 bytes

### ISSUE THREAD

**Issue by mateuszviste** [swanlizard/a72#7]
This program:
````
mov di, pktbuf
MSG db '123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567'
pktbuf DS 128
````

Makes A72 output an error "UNDEFINED SYMBOL". After some investigations I figured that A72 stops reading the file once it hits a line of more than 125 bytes.

It happens even if the line contains just a comment, like this:

````
mov di, pktbuf
; this is a very very very very very very very very very very very very very very very very very very very very very long comment
pktbuf DS 128
````

The line limitation is understandable, but the error message is very misleading. Maybe could it be more explicit, like "FILE.ASM,  2: LINE TOO LONG" ?

**Comment by swanlizard** [comment]
There's now a "line too long" error (code $0E) and line length can be adjusted via MAXLEN EQU
