### ISSUE TITLE
xor si,si is assembled differently than nasm

### ISSUE THREAD

**Issue by mateuszviste** [swanlizard/a72#8]
This is neither a bug, nor a feature request. Just reporting it in case you'd like to stick to 100% nasm compatibility.

```xor si,si``` is assembled by nasm as follows:
````
31F6                    xor si, si
````

while assembled by A72 it results in:
````
33F6		XOR SI, SI
````

both are functionally identical, so this is harmless.

**Comment by mateuszviste** [comment]
"ADD DI, CX" is also different. Nasm: "01 CF", A72: "03 F9". Again, functionally identical so not a bug.

**Comment by swanlizard** [comment]
I changed the MMODRM encoder to reflect internal parameter order which ended up generating the same code as NASM
